
package com.bancomaya.clientes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TarjetaDigitalServiceImplService", targetNamespace = "http://clientes.bancomaya.com/", wsdlLocation = "http://clientes-banco-maya-ws3.herokuapp.com/TarjetaDigital?wsdl")
public class TarjetaDigitalServiceImplService
    extends Service
{

    private final static URL TARJETADIGITALSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TARJETADIGITALSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TARJETADIGITALSERVICEIMPLSERVICE_QNAME = new QName("http://clientes.bancomaya.com/", "TarjetaDigitalServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://clientes-banco-maya-ws3.herokuapp.com/TarjetaDigital?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARJETADIGITALSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TARJETADIGITALSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TarjetaDigitalServiceImplService() {
        super(__getWsdlLocation(), TARJETADIGITALSERVICEIMPLSERVICE_QNAME);
    }

    public TarjetaDigitalServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARJETADIGITALSERVICEIMPLSERVICE_QNAME, features);
    }

    public TarjetaDigitalServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TARJETADIGITALSERVICEIMPLSERVICE_QNAME);
    }

    public TarjetaDigitalServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARJETADIGITALSERVICEIMPLSERVICE_QNAME, features);
    }

    public TarjetaDigitalServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TarjetaDigitalServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TarjetaDigitalService
     */
    @WebEndpoint(name = "TarjetaDigitalServiceImplPort")
    public TarjetaDigitalService getTarjetaDigitalServiceImplPort() {
        return super.getPort(new QName("http://clientes.bancomaya.com/", "TarjetaDigitalServiceImplPort"), TarjetaDigitalService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TarjetaDigitalService
     */
    @WebEndpoint(name = "TarjetaDigitalServiceImplPort")
    public TarjetaDigitalService getTarjetaDigitalServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://clientes.bancomaya.com/", "TarjetaDigitalServiceImplPort"), TarjetaDigitalService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARJETADIGITALSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TARJETADIGITALSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TARJETADIGITALSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
