
package com.bancomaya.clientes;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TarjetaDigitalService", targetNamespace = "http://clientes.bancomaya.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TarjetaDigitalService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.bancomaya.clientes.TarjetaDigital
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearTarjetaDigital", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.CrearTarjetaDigital")
    @ResponseWrapper(localName = "crearTarjetaDigitalResponse", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.CrearTarjetaDigitalResponse")
    public TarjetaDigital crearTarjetaDigital(
        @WebParam(name = "arg0", targetNamespace = "")
        TarjetaDigital arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bancomaya.clientes.TarjetaDigital
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTarjetaNombreCliente", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaNombreCliente")
    @ResponseWrapper(localName = "obtenerTarjetaNombreClienteResponse", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaNombreClienteResponse")
    public TarjetaDigital obtenerTarjetaNombreCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bancomaya.clientes.TarjetaDigital
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTarjetaNumero", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaNumero")
    @ResponseWrapper(localName = "obtenerTarjetaNumeroResponse", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaNumeroResponse")
    public TarjetaDigital obtenerTarjetaNumero(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bancomaya.clientes.TarjetaDigital>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTarjetaDigitales", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaDigitales")
    @ResponseWrapper(localName = "obtenerTarjetaDigitalesResponse", targetNamespace = "http://clientes.bancomaya.com/", className = "com.bancomaya.clientes.ObtenerTarjetaDigitalesResponse")
    public List<TarjetaDigital> obtenerTarjetaDigitales();

}
